### ISSUE TITLE
Scale led values

### ISSUE THREAD

**Issue by arhuaco** [matrix-io/matrix-creator-hal#1]
Hi Andrés and Kevin.

Could you normalize the scale of the LEDs somehow? This will make the everloop driver more useful.

**Comment by eighteyes** [comment]
I don't mind normalizing the scale from Matrix side. I'd rather have more
control. I suspect certain colors make more lumens then others, and white
throws it completely.

**Comment by arhuaco** [comment]
Hi @eighteyes . In any case normalizing outside Matrix side is still good in case somebody uses the LEDs via MALOS or HAL.

**Comment by eighteyes** [comment]
I'd really like to keep the 0-255 range because then it maps to web colors
nicely. That is all.

**Comment by brianofrokk3r** [comment]
+1 for @eighteyes commit, like that it maps over to web colors nicely.

**Comment by arhuaco** [comment]
It's not that the colours shouldn't range between 0 and 255. The fact is that once they reach a small numbers (say 15) the intensity is too high and it is not useful to go beyond that.

**Comment by arhuaco** [comment]
IMHO this should be fixed in HAL or in a lower layer. I've discussed this with @eljuguetero a bit.

**Comment by brianofrokk3r** [comment]
@arhuaco the intensity normalized makes sense. I agree with you.

**Comment by MexXxo** [comment]
I'm also palying with this and saw that the current maximum seems to be 50 (no documentation, so only assumed from the nodejs demo).

Offtopic:
Is there a clean way to convert RGB to RGBW?
Internet search delivered only this approach: R=R G=G B=B W=min(R, G, B)

**Comment by arhuaco** [comment]
Writing documentation for MALOS now. We should normalize the scale @eljuguetero... I wonder if the scale is linear. If we don't fix this here then we should limit the values that can be sent to MALOS because it feels weird to say that the range is [0,255] but that it doesn't make sense after 50.
