### ISSUE TITLE
/usr/bin/ld: cannot find -lasound

### ISSUE THREAD

**Issue by adrian2lee** [matrix-io/matrix-creator-hal#10]
Got following error while trying to compile with 
any advise? @kdpatino @hpsaturn 
> mkdir build && cd build && cmake .. && make
.......................
Linking CXX executable pocketsphinx_demo
/usr/bin/ld: cannot find -lasound
collect2: error: ld returned 1 exit status
demos/CMakeFiles/pocketsphinx_demo.dir/build.make:86: recipe for target 'demos/pocketsphinx_demo' failed
make[2]: *** [demos/pocketsphinx_demo] Error 1
CMakeFiles/Makefile2:490: recipe for target 'demos/CMakeFiles/pocketsphinx_demo.dir/all' failed
make[1]: *** [demos/CMakeFiles/pocketsphinx_demo.dir/all] Error 2
Makefile:117: recipe for target 'all' failed
make: *** [all] Error 2

**Comment by adrian2lee** [comment]
This got me through:

> sudo apt-get install liblapack-dev liblapack3 ibopenblas-base libopenblas-dev

**Comment by hpsaturn** [comment]
Many thanks for your feedback, I will include this dependencies on pocketsphinx deb package

**Comment by hillbicks** [comment]
I know this topic is closed, but at least for me liblapack-dev was not install together with the pocketsphinx deb package from deb http://dev-packages.matrix.one/ stable main

Another issue was that LD_LIBRARY_PATH was not set, I had to set it manually in order to get pocketsphinx to start.

**Comment by hpsaturn** [comment]
It's strange, I have not included those dependencies because in my environment the same error is not generated. I will try to replicate the problem from raspbian lite.

**Comment by hpsaturn** [comment]
From raspbian jessie lite (2016-11-25) I reproduced the same error. Right now I fixed README file. Thanks @hillbicks
