### ISSUE TITLE
Fixed 6800 Hz noise is micarray_record

### ISSUE THREAD

**Issue by marshallspight** [matrix-io/matrix-creator-hal#22]
I started with a fresh raspberry pi and a fresh matrix creator. I installed and built matrix-creator-hal and its prerequisites. The demos all work. However some of the sensors are giving low quality results. Specifically the micarray_record demo produces audible recordings but with a fixed tone around 6800 Hz on all channels. Also, the resulting 16 bit data is not centered at 0, but rather several hundred away, at some other number that varies by time and channel.

Have gotten this with two fresh pis and two fresh matrix creators.

Any tips on how to fix appreciated, or just to know that it's a known issue. Would also be happy to review my build/setup procedure to see if I did everything right.

**Comment by marshallspight** [comment]
Forgot to mention that I love the matrix creator to death. It's hands down the coolest thing I've come across in years.

**Comment by kdpatino** [comment]
Hello @marshallspight. Nice to hear that!

Did you install **matrix-creator-malos**? If you want to use the HAL examples you need to kill **malos**  service.  Just try with `sudo killall malos`.

The **malos**  service provide the support for ALSA, so instead of use HAL examples, you could record directly from ALSA with: `arecord --device=mic_channel0 -r 16000 -c 1  -f S16_LE test.wav`. Remember you could record from each physical microphone (channel 0-7) and one beamformed virtual microphone (channel 8).

Let me know how the test is going on.

Regards,

Kevin

**Comment by marshallspight** [comment]
I have not previously installed malos. (Am I reading the documentation correctly in understanding that the low-level HAL api has access to all the hardware? That's the api that most appeals to me at this point.)

After reading your reply, I decided to try malos and see what happened. I installed it and verified it was running. Then I recorded ten seconds of audio with arecord. The resulting audio had the same 6800 Hz fixed tone; it sounded just like the audio coming off of micarray_record. The audio from arecord was also not centered on 0, but offset above.

Could be a firmware problem? I have the identical problem on two different matrix-creator boards, so identical hardware failures seem unlikely.

I am unclear how to proceed from here.

**Comment by eljuguetero** [comment]
Hi,

Please share some files with recorded sounds.

ty

**Comment by marshallspight** [comment]
[audio.zip](https://github.com/matrix-io/matrix-creator-hal/files/860162/audio.zip)

Apologize for the extra zip layer; the .raw filetype wasn't supported.

**Comment by marshallspight** [comment]
I read through a lot of Troubleshooting forum posts and decided to try different power supplies. Ran the matrix creator off of my laptop batter power; also tried running off of a powered USB hub. Same results (still had the tone.)

(Also, I notice that the "yaw" reading is not working. It gives numbers but they don't track the unit's actual yaw.)

I am running out of things to try.

**Comment by milorambaldi** [comment]
Hi, Also experiencing the microphone noise problem. I uninstalled malos but the audio still has oise and offset
![image](https://user-images.githubusercontent.com/1136112/28192462-96a7fdfa-6836-11e7-95d8-976e1a3ec833.png)

**Comment by deepthpk** [comment]
I tried to use the micarray_recorder application but the saved raw files for each channel looks very noisy and also have offset from zero. Is it a H/W issue or firmware issue?
[Uploading pi3.zip…]()

**Comment by kdpatino** [comment]
Hi!

Any news about? should we close it? Let me know.

Regards,
Kevin Patino

**Comment by milorambaldi** [comment]
Still experiencing the noise and offsets. Let me know if you need test data.
Thanks

**Comment by kdpatino** [comment]
Hello @milorambaldi ,

Sure could you share your records? 

Regards,
Kevin Patino

**Comment by milorambaldi** [comment]
Thanks @kdpatino 
test data is here
[testdata.zip](https://github.com/matrix-io/matrix-creator-hal/files/1849813/testdata.zip)

Thanks

**Comment by marshallspight** [comment]
I eventually gave up on trying to use the Matrix Creator, since my
application was for the microphones and the fixed frequency noise made that
impossible. What I tried with both of them was simply installing HAL from
source, so malos never entered into it. I tried wiping and retrying a few
different ways, and nothing worked.

Recently I acquired two of the Matrix Voice. I did the same thing:
installed HAL from source. In this case, the microphones record perfectly
acceptable sound with no apparent noise. The digital audio data does not
center at 0, however. But this doesn't seem to have much effect to the ear,
and may not be an issue for my application.

At some point I intend to go back to the Creator and try again.

**Comment by kdpatino** [comment]
Hello @milorambaldi 
![screenshot from 2018-03-26 18-47-29](https://user-images.githubusercontent.com/17411203/37938981-2ea976ac-3126-11e8-8f48-d6b7b9b03296.png)

I just identify a lower volume in the record. Could you give more information about your trouble? 
Could you change the Gain value: https://github.com/matrix-io/matrix-creator-hal/blob/master/demos/micarray_recorder.cpp#L22

Also, If you could share the records from each channel. It could help us to identify the issue.
----------------------
 Hello @marshallspight 
- If you have any chance could you share with us the records from your MATRIX Creator? 
- Thanks for your valuable feedback. We will start to find the source of the offset in the records. And then fix it.

Thank You, everyone!

Regards, 

Kevin Patino

**Comment by milorambaldi** [comment]
So if you delete the output from channel 8 and amplify it, you can hear the distortion and see the offset.
![image](https://user-images.githubusercontent.com/1136112/37939319-76b5dff8-3162-11e8-96cf-2aba93868944.png)

**Comment by kdpatino** [comment]
@milorambaldi  Ok, So your issue is with the 8 channel, right? Just some points:
1- MATRIX Devices(Creator and Voice) has 8 physical microphones enumerated from 0 to 7 and the 8 channel is a virtual microphone (Beamformed Microphone). 
2- In this case, we could discard a physical damage(Hardware Issue). So, let me review the Beamforming code and try to replicate your issue.

Regards, Kevin Patino

**Comment by milorambaldi** [comment]
Sorry, i was referring to deleteing the beamformed channel 8 to maximize amplification. All the channels (0-7) experience noise and random offset.

**Comment by kdpatino** [comment]
Ok, This is a record from a MATRIX device (It has the offset but as you could check it wasn't a big level of noise)
![screenshot from 2018-03-26 19-20-26](https://user-images.githubusercontent.com/17411203/37939844-ce7129ce-312a-11e8-98fc-930e00f5e8e1.png)
Could you share your records from each channel?

Regards, Kevin

**Comment by milorambaldi** [comment]
This file contains all the channel concatenated
[demo0001-19rec-1512547740.829448.wav.zip](https://github.com/matrix-io/matrix-creator-hal/files/1849969/demo0001-19rec-1512547740.829448.wav.zip)

**Comment by milorambaldi** [comment]
Here is a different recording with the channels separated
[office2.zip](https://github.com/matrix-io/matrix-creator-hal/files/1849976/office2.zip)

**Comment by kdpatino** [comment]
Yes! a lot of noise! Ok, now we need to test your MATRIX Device. 

Could you test: https://community.matrix.one/t/matrix-creator-voice-hardware-test/1310 and https://community.matrix.one/t/hardware-test-microphones/1342

It is to be sure that you have the latest firmware. If you find noise or any problem in the recordings please contact us at alfred.gonzalez@matrixlabs.ai

Thank You!

**Comment by milorambaldi** [comment]
Programs stopped working after the upgrade. This was the initial result right after doing the steps in 1310
```
 sudo /usr/share/matrixlabs/matrixio-devices/matrix-init.bash
**** MATRIX Creator FPGA has been programmed!
./fpga_info: error while loading shared libraries: libmatrix_creator_hal.so: cannot open shared object file: No such file or directory
./fpga_info: error while loading shared libraries: libmatrix_creator_hal.so: cannot open shared object file: No such file or directory
```
I tried to solve the problem by:

`sudo apt-get install libmatrixio-creator-hal-dev`

and then got these result:

```
**** MATRIX Creator FPGA has been programmed!
IDENTIFY = 5c344e8
VERSION = 10008
*** MATRIX Creator initial process has been launched
*** Running the program instead of the bootloader
EM358 MCU was programmed before. Not programming it again.
Running the program instead of the bootloader
SAM3 MCU was programmed before. Not programming it again.

```

But now all the microphone codes are not working, just a flat line
[testdata.zip](https://github.com/matrix-io/matrix-creator-hal/files/1853217/testdata.zip)

**Comment by milorambaldi** [comment]
Upgraded to stretch and all the codes and now everything is "working" again.  I managed to run the micarray_recorder executable and produced these:
[testdata.zip](https://github.com/matrix-io/matrix-creator-hal/files/1854064/testdata.zip)

**Comment by kdpatino** [comment]
Hello @milorambaldi 
Could you register in https://community.matrix.one and send a direct message to: **kevindpatino** I could help you easier. 

Thank You!

Kevin Patino

**Comment by kdpatino** [comment]
Hello!

We found the issue, It had been fixed since this release: https://github.com/matrix-io/matrix-creator-hal/releases/tag/v0.3.1.

Regards,

Kevin Patino
