### ISSUE TITLE
Schematic for hardware components

### ISSUE THREAD

**Issue by paragshar** [matrix-io/matrix-creator-hal#23]
Hi,
Do we have a schematic available for the hardware components, and how they are wired to one another? Is that something that will be made available as open source?

**Comment by eljuligallego** [comment]
I also consider this a important document that should be available.

**Comment by marcel12bell** [comment]
Would be nice!

**Comment by Alfred-AdMobilize** [comment]
The hardware schematics for the MATRIX Creator and MATRIX Voice are not open source and are not things we would release. To allow for flexibility with our hardware we have open sourced all of the software here on Github and you are able to modify and see our code for the FPGA allowing you to do almost anything you'd like.

**Comment by dkorenkovnl** [comment]
@AlieGG have not changed your mind?
it would be great to have schema for whom who is about to use MATRIX Voice as fpga board.
thanks!
