### ISSUE TITLE
always return 0 when run ./mic_demo

### ISSUE THREAD

**Issue by arleneF** [matrix-io/matrix-creator-hal#26]
Hi all,
when I run the file "mic_demo" under matrix-creator-hal/build/demo, the output shown in terminal is always zero.

Thanks,
Arlene

**Comment by kdpatino** [comment]
Hello @arleneF ,

It's normal, try to set a 1KHz tone near of each microphone and you could see the numbers start to change. Check also our community page: http://community.matrix.one/t/mic-demo-not-working/246/6

Let me know if you need more help.

Regards,
Kevin
