### ISSUE TITLE
Direction of Arrival

### ISSUE THREAD

**Issue by aalanwar** [matrix-io/matrix-creator-hal#28]
Hi,

Thanks for your efforts in maintaining and organizing this repo. 
I would like to ask about the direction of arrival demo. I tried it and monitor the leds colors and the printed angles. It gave me  wrong directions and it is not stable at all.  The values keep changing while having the same voice in the room.
How can I get accurate and stable results?

Thanks in Advance!

**Comment by RHZhang** [comment]
The DOA algorithm is a little bit basic here... Maybe we need to implement some dereverberation algorithm by our own... :(

**Comment by reinzor** [comment]
I will send a PR for a more stable DOA algorithm soon

**Comment by kdpatino** [comment]
Thank You @reinzor. Should we close this issue? Any insights about the DOA algorithm? 
Let me know.

Kevin Patino

**Comment by reinzor** [comment]
Issue can be closed. Description of the DOA algorithm is given in the PR: https://github.com/matrix-io/matrix-creator-hal/pull/49
