### ISSUE TITLE
Sampling Rate

### ISSUE THREAD

**Issue by aalanwar** [matrix-io/matrix-creator-hal#29]
Hi,

Excuse me, I would like to ask about the sampling rate which is used in the "[micarray_recorder](https://github.com/matrix-io/matrix-creator-hal/blob/ff84fb33f74c2e4a7358959691083833884f63bf/demos/micarray_recorder.cpp)" Demo?
I reduced the time to 5 seconds and build so
uint16_t seconds_to_record = 5;
And I am getting 160000 samples for every channel, which means that the sampling rate is 
160000/5 = 32000
Am I missing some thing?

I notice this definition in this [file ](https://github.com/matrix-io/matrix-creator-hal/blob/ff84fb33f74c2e4a7358959691083833884f63bf/cpp/driver/microphone_array.h)
const uint32_t kSamplingRate = 16000;

What is wrong? Could you please clarify ?

**Comment by RHZhang** [comment]
The sampling rate is fix to 16000. So if you just need 5 seconds data, you will get 5*16000 for one channel; and you will get 5*16000*8 "int16_t" for all channels.

**Comment by kdpatino** [comment]
Hello!

Now we support frequencies from 8KHz to 96KHz let's check  https://github.com/matrix-io/matrix-creator-hal/blob/master/cpp/driver/microphone_array.h#L31. 

Also, You could check the Kernel driver implementation:
https://github.com/matrix-io/matrixio-kernel-modules

Regards,

Kevin Patino
