### ISSUE TITLE
humidity and temp values always 0

### ISSUE THREAD

**Issue by lpotter** [matrix-io/matrix-creator-hal#3]
I tried getting humidity and temperature values thus:

  hal::WishboneBus* bus = new hal::WishboneBus();
  bus->SpiInit();
  hal::HumiditySensor humidity_sensor;
  humidity_sensor.Setup(bus);

  hal::HumidityData humidity_data;
  humidity_sensor.Read(&humidity_data);

  std::cout << "humidity = " << humidity_data.humidity << "\t";
  std::cout << "temperature = " << humidity_data.temperature << std::endl;

both humidity and temperature are always 0.

**Comment by eljuguetero** [comment]
Hi Ipotter, we're fixing this bug, it is a software issue

**Comment by eljuguetero** [comment]
Hi Ipotter, 

Fixed.

1. update the HAL
2. `sudo apt-get update && sudo apt-get upgrade`
3. `sudo reboot`
