### ISSUE TITLE
Error when doing cmake ..

### ISSUE THREAD

**Issue by Mn0491** [matrix-io/matrix-creator-hal#33]
CMake Error: The following variables are used in this project, but they are set to NOTFOUND.
Please set them or make sure they are set and tested correctly in the CMake files:
FFTW_LIBRARIES
    linked by target "direction_of_arrival_demo" in directory /home/pi/matrix-creator-hal/demos
    linked by target "matrix_creator_hal" in directory /home/pi/matrix-creator-hal/cpp/driver

-- Configuring incomplete, errors occurred!
See also "/home/pi/matrix-creator-hal/build/CMakeFiles/CMakeOutput.log".
See also "/home/pi/matrix-creator-hal/build/CMakeFiles/CMakeError.log".

**Comment by RHZhang** [comment]
You need to install FFTW firstly... 
Just like using this command (you can see this in readme.md page):
sudo apt-get install cmake g++ git libfftw3-dev wiringpi
