### ISSUE TITLE
Error Compiling matrix-hal

### ISSUE THREAD

**Issue by llangar** [matrix-io/matrix-creator-hal#37]
Hello everyone!!

-- * * * A D M O B I L I Z E * * *
-- Admobilize: Please treat warnings as errors. Use: -DADM_FATAL_WARNINGS=ON
-- * * * * * * * * * * * * * * * *
-- * * * A D M O B I L I Z E * * *
-- Admobilize: Please treat warnings as errors. Use: -DADM_FATAL_WARNINGS=ON
-- * * * * * * * * * * * * * * * *
-- gflags found =>GFLAGS_LIB-NOTFOUND
-- * * * A D M O B I L I Z E * * *
-- Admobilize: Please treat warnings as errors. Use: -DADM_FATAL_WARNINGS=ON
-- * * * * * * * * * * * * * * * *
CMake Error: The following variables are used in this project, but they are set to NOTFOUND.
Please set them or make sure they are set and tested correctly in the CMake files:
GFLAGS_LIB
    linked by target "micarray_recorder" in directory /home/pi/matrix-creator-hal/demos

-- Configuring incomplete, errors occurred!
See also "/home/pi/matrix-creator-hal/build/CMakeFiles/CMakeOutput.log".
See also "/home/pi/matrix-creator-hal/build/CMakeFiles/CMakeError.log".

Any sugestion of this issue?

**Comment by kdpatino** [comment]
Hello @llangar 

Please try with: `sudo apt-get install libgflags-dev` and then try to compile.

Let me know if you need anything else :+1: 

Regards,
Kevin

**Comment by llangar** [comment]
It Works!!!

Thank you very much!!  👍
