### ISSUE TITLE
Floating point execption

### ISSUE THREAD

**Issue by deepthpk** [matrix-io/matrix-creator-hal#41]
Hi,
hen i run the mic demos after installing the latest matrix creator hal software, i can see that it throws floating point exception, Could you let me know if there is a solution ?

**Comment by MasonP57** [comment]
I installed all the HAL software today, October 6th 2017. None of the demos work and I also receive floating point exception for several of the demos, including the micarray_recorder.

everloop_demo also doens't work. sensors_demo will run but only displays a value of 0 for everything.

**Comment by kdpatino** [comment]
Hello @MasonP57 Could you install matrix-creator-init with: 
```
# Add repo and key
curl https://apt.matrix.one/doc/apt-key.gpg | sudo apt-key add -
echo "deb https://apt.matrix.one/raspbian $(lsb_release -sc) main" | sudo tee /etc/apt/sources.list.d/matrixlabs.list

# Update packages and install
sudo apt-get update
sudo apt-get upgrade

# Installation
sudo apt install matrixio-creator-init
```
Please let me know how it works. Now we are working in the new documentation.

Regards,

Kevin Patino

**Comment by MasonP57** [comment]
How can I remove the matrix-creator-init?

**Comment by kdpatino** [comment]
Hello @MasonP57 

Could you try with `sudo apt-get remove --purge matrix-creator-init`

Regards,

Kevin

**Comment by MasonP57** [comment]
"""
sudo apt install matrixio-creator-init
Reading package lists... Done
Building dependency tree
Reading state information... Done
E: Unable to locate package matrixio-creator-init
"""

That's what I get after removing and then installing using your instructions.

**Comment by MasonP57** [comment]
Thanks for the help Kevin. After following your instructions I have the Matrix HAL demos working. The MOS stuff all stopped working though but I'll make a new issue for that after I do some more testing.

**Comment by kwiatks** [comment]
See http://community.matrix.one/t/solved-support-of-debian-stretch/760/5 for step by step instructions on getting this working.  I too had the Floating Point issue.  It's essential you do a reboot at the end of the following all the items.

**Comment by kdpatino** [comment]
Hello,

Should we close this issue? We added error handling messages.

Regards,
Kevin Patino
