### ISSUE TITLE
Error Compiling matrix-hal using make 

### ISSUE THREAD

**Issue by maydali28** [matrix-io/matrix-creator-hal#46]
Hello everyone!!
[ 45%] Building CXX object demos/driver/CMakeFiles/matrix_creator_hal.dir/uart_control.cpp.o
Linking CXX static library libmatrix_creator_hal.a
Error running link command: No such file or directory
demos/driver/CMakeFiles/matrix_creator_hal.dir/build.make:410: recipe for target 'demos/driver/libmatrix_creator_hal.a' failed
make[2]: *** [demos/driver/libmatrix_creator_hal.a] Error 2
CMakeFiles/Makefile2:719: recipe for target 'demos/driver/CMakeFiles/matrix_creator_hal.dir/all' failed
make[1]: *** [demos/driver/CMakeFiles/matrix_creator_hal.dir/all] Error 2
Makefile:117: recipe for target 'all' failed
make: *** [all] Error 2

**Comment by kdpatino** [comment]
Hello @maydali28 ,

Could you build it? Did you test the last release? Let me know if you need any help.

Regards,
Kevin Patino
