### ISSUE TITLE
Get Timestamp from Mics.Read()

### ISSUE THREAD

**Issue by Beeze** [matrix-io/matrix-creator-hal#47]
Hello:

I'm interested in getting the db level of the sound recorded by each microphone, accompanied by the timestamp at which this was recorded. 

The goal of this is to use all the data, to uncover when the microphone recorded an audio sample, and use this to calculate an angle believed to be closest to the audio source. 

What needs to be updated in order to attain this information?

The reason I need this data is so that I can build out this logic from scratch for our use case.

**Comment by kdpatino** [comment]
Hello @Beeze ,

Unfortunately, MATRIX Devices don't manage the timestamps. You could get it from the linux userspace. Check the following links, it could help you to reach your goal:

https://stackoverflow.com/questions/11765301/how-do-i-get-the-unix-timestamp-in-c-as-an-int
http://en.cppreference.com/w/cpp/chrono

Regards,
Kevin Patino
