### ISSUE TITLE
PWM output from GPIO

### ISSUE THREAD

**Issue by Beeze** [matrix-io/matrix-creator-hal#52]
I'm trying to test using PWM on gpio pins 0-9, using the gpio_demo as my starting part, but am having trouble reading the output (4-bit hex value). Can you give me some insight into what this demo is outputting?

**Comment by kdpatino** [comment]
Hello @Beeze did you check the last release. https://github.com/matrix-io/matrix-creator-hal/releases/tag/v0.2.3 it includes a PWM demo. 

Regards,

Kevin Patino
