### ISSUE TITLE
Make during installation gives an Error

### ISSUE THREAD

**Issue by CarneiroDiogo** [matrix-io/matrix-creator-hal#66]
This is the error i get when using make:

[ 35%] Linking CXX executable servo_demo
/usr/local/lib/libwiringPi.so: undefined reference to `shm_open'
collect2: error: ld returned 1 exit status
demos/CMakeFiles/servo_demo.dir/build.make:99: recipe for target 'demos/servo_demo' failed
make[2]: *** [demos/servo_demo] Error 1
CMakeFiles/Makefile2:123: recipe for target 'demos/CMakeFiles/servo_demo.dir/all' failed
make[1]: *** [demos/CMakeFiles/servo_demo.dir/all] Error 2
Makefile:127: recipe for target 'all' failed
make: *** [all] Error 2

 I'm using matrix creator with raspberry pi. Can someone help?
Thanks in advance

**Comment by CarneiroDiogo** [comment]
Hello Kevin,
Thanks for your response, I was able to solve the problem by formatting the raspberry and use a different distro (NOOBS). Everything is working now.

Best Regards,

Diogo Carneiro


De: Kevin Patino [mailto:notifications@github.com]
Enviada: 12 de abril de 2018 15:23
Para: matrix-io/matrix-creator-hal <matrix-creator-hal@noreply.github.com>
Cc: Carneiro Diogo (BrgP/ENG-P) <Diogo.Carneiro@pt.bosch.com>; Mention <mention@noreply.github.com>
Assunto: Re: [matrix-io/matrix-creator-hal] Make during installation gives an Error (#66)


Hello @CarneiroDiogo<https://github.com/CarneiroDiogo>

Did you install the dependencies? Could you try with:

sudo apt-get install cmake g++ git libfftw3-dev wiringpi matrixio-creator-init libgflags-dev

Regards,

Kevin Patino

**Comment by kdpatino** [comment]
Glad to hear it!
