### ISSUE TITLE
cpp/driver/microphone_array_location.h different to the one shown by qgit !?!

### ISSUE THREAD

**Issue by Philius** [matrix-io/matrix-creator-hal#89]
When looking into using the Matric voice microphone locations I re-cloned your repo to see what's changed.
When I opened the file on disk I saw the familiar Matrix Creator locations so I had a look at the version history in qgit.
The most recent version of microphone_array_location.h has changes in it to detect what device your code is running on to pick the correct mic locations at runtime, something I want.

I checked this twice!
```
git clone https://github.com/matrix-io/matrix-creator-hal.git
cd matrix-creator-hal
qgit
```
If I press 'T' to get the directory tree  view and double-click microphone_array_location.h it shows the most recent version to be from origin/bes/miclocation 2018-07-18 15:44.

Going through the rev list the file wasn't modified since then, but somehow it is!
Also, when launched from the command line, I see the following:

> ASSERT getFileAnnotation: no revision 82ed19fbd4202ded32a75990136a2407bb8a76d4
> ASSERT in doAnnotate: annotation for 82ed19fbd4202ded32a75990136a2407bb8a76d4 not valid
> ASSERT in lookupAnnotation: no annotation for cpp/driver/microphone_array_location.h
>

**Comment by BSpwr** [comment]
Hi, this should be merged shortly.
Thanks for bringing it to our attention.
