### ISSUE TITLE
certificate has expired

### ISSUE THREAD

**Issue by moh-yismail** [matrix-io/matrix-creator-hal#94]
curl https://apt.matrix.one/doc/apt-key.gpg | sudo apt-key add -
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed
  0     0    0     0    0     0      0      0 --:--:-- --:--:-- --:--:--     0
curl: (60) SSL certificate problem: certificate has expired
More details here: https://curl.haxx.se/docs/sslcerts.html

curl failed to verify the legitimacy of the server and therefore could not
establish a secure connection to it. To learn more about this situation and
how to fix it, please visit the web page mentioned above.
gpg: no valid OpenPGP data found.

**Comment by Hermitter** [comment]
Thanks for bringing this up! The issue should be fixed from our end now.
