### ISSUE TITLE
what does the gyroscope value mean?

### ISSUE THREAD

**Issue by sunwell1994** [matrix-io/matrix-creator-hal#95]
it shows positive gyroscope values
///////////////////////
 [ IMU Sensor Output ]
 [ Acceleration In X : -0.06 ] [ Acceleration In Y : 0.126 ] [ Acceleration In Z : 0.965 ]
 [ Gyroscope In X : 5.981 ] [ Gyroscope In Y : 5.981 ] [ Gyroscope In Z : 0.897 ]
 [ Yaw : 88.903 ] [ Pitch : 3.52798 ] [ Roll : 7.43902 ]
 [ Magnetometer in X : -0.009 ] [ Magnetometer in Y : 0.47 ] [ Magnetometer in Z : -0.33 ]

even though it is static

**Comment by samreenislam** [comment]
Gyroscope unit is dps, please see [here](https://community.matrix.one/t/what-are-the-units-of-imu-sensor-values/2971).
