### ISSUE TITLE
Can't install due to 'no valid opengpg data found'

### ISSUE THREAD

**Issue by sharmrinal** [matrix-io/matrix-creator-hal#98]
curl https://apt.matrix.one/doc/apt-key.gpg | sudo apt-key add -
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed
100   252  100   252    0     0   2739      0 --:--:-- --:--:-- --:--:--  2739
gpg: no valid OpenPGP data found.

**Comment by trecetp** [comment]
Hi

You can find the solution here https://community.matrix.one/t/pubkey-not-available/3265/3?u=trecetp

Regards
